name: Push to Gitlab

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push to Gitlab
      uses: phaus/gitlab-push-action@master
      with:
        args: "https://gitlab.com/<namespace>/<repository>"
      env:
        GITLAB_HOST: "git-lab.de"
        GITLAB_REPOSITORY: "git@git-lab.de:meta-view/homepage.git"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SRC_BRANCH: ${{ env.SRC_BRANCH }}
        DST_BRANCH: ${{ env.DST_BRANCH }}
